from http.server import BaseHTTPRequestHandler
import json
import urllib.parse as urlparse
from urllib.parse import parse_qs
from datetime import datetime

try:
    from database import get_connection, return_connection
except ImportError:
    import sys
    sys.path.append('..')
    from database import get_connection, return_connection

class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        # Parse query parameters
        parsed_path = urlparse.urlparse(self.path)
        query_params = parse_qs(parsed_path.query)
        
        password = query_params.get('password', [''])[0]
        
        # Verify password
        if password != '1542':
            self.send_response(401)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': False,
                'error': 'Unauthorized: Invalid password'
            }).encode('utf-8'))
            return
        
        # Fetch contacts from database
        conn = get_connection()
        if conn:
            try:
                cur = conn.cursor()
                cur.execute("SELECT name, phone, created_at FROM contacts ORDER BY name")
                contacts = cur.fetchall()
                cur.close()
                
                if not contacts:
                    self.send_response(404)
                    self.send_header('Content-type', 'application/json')
                    self.end_headers()
                    self.wfile.write(json.dumps({
                        'success': False,
                        'error': 'No contacts found'
                    }).encode('utf-8'))
                    return
                
                # Generate VCF content
                vcf_content = ""
                vcf_content += "BEGIN:VCARD\n"
                vcf_content += "VERSION:3.0\n"
                vcf_content += f"PRODID:-//STATUS VIEWS CENTRE//VCF Generator 1.0//EN\n"
                
                for i, contact in enumerate(contacts, 1):
                    name = contact[0]
                    phone = contact[1]
                    created_at = contact[2]
                    
                    # Format phone number (remove spaces and special characters)
                    formatted_phone = ''.join(filter(str.isdigit, phone))
                    
                    vcf_content += f"\nBEGIN:VCARD\n"
                    vcf_content += f"VERSION:3.0\n"
                    vcf_content += f"FN:{name}\n"
                    vcf_content += f"N:;{name};;;\n"
                    vcf_content += f"TEL;TYPE=CELL,VOICE:{formatted_phone}\n"
                    
                    # Add timestamp if available
                    if created_at:
                        timestamp = created_at.strftime("%Y%m%dT%H%M%SZ")
                        vcf_content += f"REV:{timestamp}\n"
                    
                    # Add note about source
                    vcf_content += f"NOTE:Contact from STATUS VIEWS CENTRE\n"
                    vcf_content += f"UID:STATUS-VIEWS-{i:04d}\n"
                    vcf_content += f"END:VCARD\n"
                
                # Add footer
                vcf_content += f"\n; Generated by STATUS VIEWS CENTRE\n"
                vcf_content += f"; Total Contacts: {len(contacts)}\n"
                vcf_content += f"; Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
                
                # Send VCF file
                filename = f"status_views_contacts_{datetime.now().strftime('%Y%m%d_%H%M%S')}.vcf"
                
                self.send_response(200)
                self.send_header('Content-type', 'text/vcard')
                self.send_header('Content-Disposition', f'attachment; filename="{filename}"')
                self.send_header('X-Total-Contacts', str(len(contacts)))
                self.send_header('X-Generated-At', datetime.now().isoformat())
                self.end_headers()
                self.wfile.write(vcf_content.encode('utf-8'))
                
            except Exception as e:
                self.send_response(500)
                self.send_header('Content-type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({
                    'success': False,
                    'error': f'Error generating VCF: {str(e)}'
                }).encode('utf-8'))
            finally:
                return_connection(conn)
        else:
            self.send_response(500)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': False,
                'error': 'Database connection failed'
            }).encode('utf-8'))