from http.server import BaseHTTPRequestHandler
import json
import urllib.parse as urlparse
from urllib.parse import parse_qs
from datetime import datetime
import base64
import os

try:
    from database import get_connection, return_connection
    from config import ADMIN_USERNAME, ADMIN_PASSWORD, VCF_PREFIX
except ImportError:
    import sys
    sys.path.append('..')
    from database import get_connection, return_connection
    # fallback config from env
    ADMIN_USERNAME = os.environ.get('ADMIN_USERNAME', 'admin')
    ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD', '1542')
    VCF_PREFIX = os.environ.get('VCF_PREFIX', 'status_views_contacts')

def check_basic_auth(headers):
    auth = headers.get('Authorization', '')
    if not auth or not auth.startswith('Basic '):
        return False
    try:
        token = auth.split(' ', 1)[1]
        decoded = base64.b64decode(token).decode('utf-8')
        user, pwd = decoded.split(':', 1)
        return user == ADMIN_USERNAME and pwd == ADMIN_PASSWORD
    except Exception:
        return False

class handler(BaseHTTPRequestHandler):
    def do_GET(self):
        # Admin-only
        if not check_basic_auth(self.headers):
            self.send_response(401)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': False,
                'error': 'Unauthorized: admin credentials required'
            }).encode('utf-8'))
            return

        conn = get_connection()
        if conn:
            try:
                cur = conn.cursor()
                cur.execute("SELECT name, phone, created_at FROM contacts ORDER BY name")
                contacts = cur.fetchall()
                cur.close()

                if not contacts:
                    self.send_response(404)
                    self.send_header('Content-type', 'application/json')
                    self.end_headers()
                    self.wfile.write(json.dumps({
                        'success': False,
                        'error': 'No contacts found'
                    }).encode('utf-8'))
                    return

                vcf_parts = []
                for i, contact in enumerate(contacts, 1):
                    name = contact[0] or ''
                    phone = contact[1] or ''
                    created_at = contact[2]

                    formatted_phone = ''.join(filter(str.isdigit, phone))

                    v = []
                    v.append("BEGIN:VCARD")
                    v.append("VERSION:3.0")
                    v.append(f"FN:{name}")
                    v.append(f"N:;{name};;;")
                    v.append(f"TEL;TYPE=CELL,VOICE:{formatted_phone}")
                    if created_at:
                        try:
                            timestamp = created_at.strftime("%Y%m%dT%H%M%SZ")
                            v.append(f"REV:{timestamp}")
                        except Exception:
                            pass
                    v.append("NOTE:Contact from STATUS VIEWS CENTRE")
                    v.append(f"UID:STATUS-VIEWS-{i:04d}")
                    v.append("END:VCARD")
                    vcf_parts.append("\\n".join(v))

                vcf_content = "\\n".join(vcf_parts)
                vcf_content += f"\\n\\n; Generated by STATUS VIEWS CENTRE\\n"
                vcf_content += f"; Total Contacts: {len(contacts)}\\n"
                vcf_content += f"; Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\\n"

                filename = f"{VCF_PREFIX}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.vcf"

                self.send_response(200)
                self.send_header('Content-type', 'text/vcard')
                self.send_header('Content-Disposition', f'attachment; filename=\"{filename}\"')
                self.send_header('X-Total-Contacts', str(len(contacts)))
                self.send_header('X-Generated-At', datetime.now().isoformat())
                self.end_headers()
                self.wfile.write(vcf_content.encode('utf-8'))

            except Exception as e:
                self.send_response(500)
                self.send_header('Content-type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({
                    'success': False,
                    'error': f'Error generating VCF: {str(e)}'
                }).encode('utf-8'))
            finally:
                return_connection(conn)
        else:
            self.send_response(500)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({
                'success': False,
                'error': 'Database connection failed'
            }).encode('utf-8'))